### ISSUE TITLE
please list supported formats

### ISSUE THREAD

**Issue by Musickiller** [TheStaticTurtle/Wisp-Desktop#2]
Hi again!

I have a book in .m4b format, it also has a .cue file, but neither seem to be recognized by this app. Could you please add a list of supported formats to the ReadMe? Thanks!

Kind Regards,
Dmitrii

**Comment by TheStaticTurtle** [comment]
Hi, 
I've updated the readme, I've never heard of the m4b and cue formats I'm not sure how these work.
Samuel.
